--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Layton-L/PromoSystem
build-by-default: true
branches:
- master
projects:
  PromoSystem:
    path: ""
    libs:
    - src: jojoe77777\FormAPI\libFormAPI
      version: ^2.1.0
      branch: master
...
