name: PromoSystem
main: PromoSystem\Layton\PromoSystem
api: 4.0.0

version: 2.2
author: Layton
php: 8.0

permissions:
  promosystem.promo:
    default: true
  promosystem.admin:
    default: op
  promosystem.languages:
    default: op
