---
# sqlite3 / mysql
provider: "sqlite3"

provider_settings:
  host: "localhost"
  user: "root"
  password: ""
  db: "promosystem"

# eng / rus
language: "eng"
custom_translations_enabled: true

promo:
  minimum_length: 5
  maximum_length: 10
...